### ISSUE TITLE
Updating to new usage

### ISSUE THREAD

**Issue by mhkeller** [debrouwere/google-analytics#20]
I'm trying to update to the new usage per https://github.com/debrouwere/google-analytics/issues/19

I attempted this: https://github.com/newslynx/newslynx-sc-google-analytics/commit/0e3131e3c6347fd6c0d0dd31647e14a100fb0461

But I think it needs something closer to the `.set` pattern as described here: https://github.com/debrouwere/google-analytics/wiki/Querying#querying-closer-to-the-metal

Could you advise on how to do this with the current version 0.21.4?

**Comment by mhkeller** [comment]
Tracking here with more tracebacks: https://github.com/newslynx/opportunities/issues/114

**Comment by debrouwere** [comment]
Sorry for the late response Michael, only reading this now.

The one big difference with the new version is that you can no longer specify metrics and dimensions at the same time, as you used to be able to do. Also note that different metrics are specified as sequential arguments, rather than as a single list of metrics. (This has always been the case for the `metrics` and `dimensions` methods but not for the no-longer-in-existence `query` method, which took a list of metrics as its first argument and a list of dimensions as its second argument. This was the main reason for changing the interface: it was confusing to have these two approaches co-exist.)

So for example in the code you reference

```python
prof.core.query.metrics(self.METRICS.keys(), self.DIMENSIONS.keys())
```

which should become

```python
prof.core.query.metrics(*self.METRICS.keys()).dimensions(*self.DIMENSIONS.keys())
```

Notice both the split into `metrics` and `dimensions` and the splat `*`.

FWIW, the API is pretty close to what I want for 1.0 at this point :)
